Remove redundant diff -u

diff --git a/.test/task1/validate b/.test/task1/validate
--- a/.test/task1/validate
+++ b/.test/task1/validate
@@ -48,7 +48,7 @@ function check_version() {
     echo "$ACTUAL"
     fail
   fi
-  diff -u --color=always -U 1000 <(echo "$EXPECTED") <(echo "$ACTUAL") || fail
+  diff --color=always -U 1000 <(echo "$EXPECTED") <(echo "$ACTUAL") || fail
 }
 
 
@@ -70,14 +70,14 @@ echo "Test case #3 (no changes outside of 'build' after make)"
 assert_has_changes
 make -s
 assert_no_changes
-diff -u --color=always -qr --exclude=build "$ROOT_DIR" "$TMP_DIR" || fail
+diff --color=always -qr --exclude=build "$ROOT_DIR" "$TMP_DIR" || fail
 
 echo "Test case #4 (no changes outside of 'build' after make clean)"
 
 assert_no_changes
 make -s clean
 assert_has_changes
-diff -u --color=always -qr --exclude=build "$ROOT_DIR" "$TMP_DIR" || fail
+diff --color=always -qr --exclude=build "$ROOT_DIR" "$TMP_DIR" || fail
 
 echo "Test case #5 (make all)"
 
diff --git a/.test/task2/validate b/.test/task2/validate
--- a/.test/task2/validate
+++ b/.test/task2/validate
@@ -44,7 +44,7 @@ function check_empty_test_output() {
     echo "$ACTUAL"
     fail
   fi
-  diff -u --color=always -U 1000 <(echo "$EXPECTED") <(echo "$ACTUAL") || fail
+  diff --color=always -U 1000 <(echo "$EXPECTED") <(echo "$ACTUAL") || fail
 }
 
 function check_test_output_contains() {
@@ -90,7 +90,7 @@ echo "Test case #4 (no changes outside of 'build' after make check)"
 assert_no_changes
 make check
 assert_no_changes
-diff -u --color=always -qr --exclude=build "$ROOT_DIR" "$TMP_DIR" || fail
+diff --color=always -qr --exclude=build "$ROOT_DIR" "$TMP_DIR" || fail
 
 echo "Test case #5 (make check fails for incorrect tests)"
 
diff --git a/.test/task3/validate b/.test/task3/validate
--- a/.test/task3/validate
+++ b/.test/task3/validate
@@ -45,7 +45,7 @@ function check_docker_test() {
     echo "$ACTUAL"
     fail
   fi
-  diff -u --color=always -U 1000 <(echo "$EXPECTED") <(echo "$ACTUAL") || fail
+  diff --color=always -U 1000 <(echo "$EXPECTED") <(echo "$ACTUAL") || fail
 }
 
 
